config/routes.rb
Rails.application.routes.draw do
  root 'clientes#index'

  resources :clientes
  resources :vencimentos

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	#attr_accessible :nome
	has_many :vencimento
	validates :nome, presence: true, length: {minimum: 5}
end

app/models/vencimento.rb
class Vencimento < ActiveRecord::Base
  belongs_to :cliente
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
	def index
		@clientes = Cliente.paginate(:page => params[:page], :per_page => 2)
	end

	def new 
		@cliente = Cliente.new
	end

	def create
		#render plain: params[:cliente].inspect 
		@cliente = Cliente.new( cliente_params )
		if @cliente.save
			redirect_to @cliente
		else
			render 'new'
		end
		
	end

	def show
		@cliente = Cliente.find(params[:id])
	end

	def edit
		@cliente = Cliente.find(params[:id])
	end

	def update
		@cliente = Cliente.find(params[:id])

		if @cliente.update(cliente_params)
			redirect_to @cliente
		else
			render 'edit'
		end
	end

	def destroy
		@cliente = Cliente.find(params[:id])
		@cliente.destroy

		redirect_to clientes_path
	end

	private
	def cliente_params
		params.require(:cliente).permit(:nome, :email)
	end
end

app/controllers/vencimentos_controller.rb
class VencimentosController < ApplicationController
	def index
		@vencimentos = Vencimento.all
		#render plain: @vencimentos.inspect 
	end

	def create
		#render plain: params[:cliente].inspect 
		@vencimento = Vencimento.new( vencimento_params )
		if @vencimento.save
			redirect_to @vencimento
		else
			render 'new'
		end
		
	end

	def show 
		@vencimento = Vencimento.find(params[:id])
	end

	def edit 
		@vencimento = Vencimento.find(params[:id])
	end

	def update
		@vencimento = Vencimento.find(params[:id])

		if @vencimento.update(vencimento_params)
			redirect_to @vencimento
		else
			render 'edit'
		end
	end

	private
	def vencimento_params
		params.require(:vencimento).permit(:valor, :dia, :cliente_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/vencimentos_helper.rb
module VencimentosHelper
end

app/views/clientes/edit.html.erb
<h3>Editar Cliente</h3>

<%= form_for :cliente, url: cliente_path(@cliente), method: :patch do |f| %>

<% if @cliente.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@cliente.errors.count, 'erro') %> proibe que o cliente seja salvo: </h2>

		<ul>
			<% @cliente.errors.full_messages.each do |msg| %>
			<li><%=msg%></li>
			<% end %>
		</ul>
	</div>
<% end %>

<p>
	<%= f.label :nome	%><br>
	<%= f.text_field :nome	%>
</p>
<p>
	<%= f.label :email	%><br>
	<%= f.text_field :email	%>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

<%= link_to 'Voltar', clientes_path %>

app/views/clientes/index.html.erb
<h3>Clientes</h3>

<%= link_to 'Novo Cliente', new_cliente_path %>

<table border='1'>
	<tr>
		<th>Nome</th>
		<th>E-mail</th>
		<th>...</th>
	</tr>


<% @clientes.each do |cliente| %>
<tr>
	<td><%= cliente.nome %></td>
	<td><%= cliente.email %></td>
	<td>
		<%= link_to 'Ver', cliente_path(cliente) %> |
		<%= link_to 'Editar', edit_cliente_path(cliente) %> |
		<%= link_to 'Excluir', cliente_path(cliente), method: :delete, data: {confirm: 'Quer mesmo excluir esse cliente?'} %>
	</td>
</tr>
<% end %>
</table>

<%= will_paginate @clientes %>

app/views/clientes/new.html.erb
<h3>Cadastrar Cliente</h3>

<%= form_for :cliente, url: clientes_path do |f| %>

<% if @cliente.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@cliente.errors.count, 'erro') %> proibe que o cliente seja salvo: </h2>

		<ul>
			<% @cliente.errors.full_messages.each do |msg| %>
			<li><%=msg%></li>
			<% end %>
		</ul>
	</div>
<% end %>

<p>
	<%= f.label :nome	%><br>
	<%= f.text_field :nome	%>
</p>
<p>
	<%= f.label :email	%><br>
	<%= f.text_field :email	%>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

<%= link_to 'Voltar', clientes_path %>

app/views/clientes/show.html.erb
<p>Nome:<%=@cliente.nome%></p>
<p>Email:<%=@cliente.email%></p>
<%= link_to 'Voltar', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
	<li><%= link_to 'Clientes', clientes_path %></li>
	<li><%= link_to 'Vencimentos', vencimentos_path %></li>
</ul>


<br>

<%= yield %>

</body>
</html>

app/views/vencimentos/edit.html.erb
<h3>Cadastrar Vencimento</h3>

<%= form_for :vencimento, url: vencimento_path(@vencimento), method: :patch do |f|%>

<p>
	<%= f.label :cliente %><br>
	<%= collection_select(:vencimento, :cliente_id, Cliente.all, :id, :nome) %>
</p>

<p>
	<%= f.label :valor %><br>
	<%= f.text_field :valor %>
</p>

<p>
	<%= f.label :dia %><br>
	<%= f.text_field :dia %>
</p>

<p>
	<%= f.submit  %>
</p>
<% end %>

app/views/vencimentos/index.html.erb
<h3>Vencimentos</h3>

<%= link_to 'Novo Vencimento', new_vencimento_path %>

<table border='1'>
	<tr>
		<th>Cliente</th>
		<th>Dia</th>
		<th>Valor</th>
		<th>...</th>
	</tr>


<% @vencimentos.each do |vencimento| %>
<tr>
	<td><%= vencimento.cliente.nome if vencimento.cliente %></td>
	<td><%= vencimento.dia %></td>
	<td><%= vencimento.valor %></td>
	<td>
		<%= link_to 'Ver', vencimento_path(vencimento) %> |
		<%= link_to 'Editar', edit_vencimento_path(vencimento) %> |
		<%= link_to 'Excluir', vencimento_path(vencimento), method: :delete, data: {confirm: 'Quer mesmo excluir esse cliente?'} %>
	</td>
</tr>
<% end %>
</table>

app/views/vencimentos/new.html.erb
<h3>Cadastrar Vencimento</h3>

<%= form_for :vencimento, url: vencimentos_path do |f|%>

<p>
	<%= f.label :cliente %><br>
	<%= collection_select(:vencimento, :cliente_id, Cliente.all, :id, :nome) %>
</p>

<p>
	<%= f.label :valor %><br>
	<%= f.text_field :valor %>
</p>

<p>
	<%= f.label :dia %><br>
	<%= f.text_field :dia %>
</p>

<p>
	<%= f.submit  %>
</p>
<% end %>

app/views/vencimentos/show.html.erb
<p>Dia: <%=@vencimento.dia%></p>
<p>Valor: <%=@vencimento.valor%></p>

<%= link_to 'Voltar', vencimentos_path %>